### ISSUE TITLE
Hidden Directories should be Hidden

### ISSUE THREAD

**Issue by RyanGreenup** [Yvee1/hascard#2]
When trying to import a file it can be difficult to find files between hidden directories, this should be toggled with <kbd>Ctrl</kbd>+<kbd>h</kbd> see for example this screenshot:

![image](https://user-images.githubusercontent.com/47832594/88002655-5c9a8080-cb46-11ea-8273-07bda2bbbcdd.png)

**Comment by RyanGreenup** [comment]
Also it doesn't appear to show symlinks, I have, for example `~/Notes` --> `~/Dropbox/Notes`, and I'm sure others do to, it would be really nice if that was fixed.

(excellent work by the way!)

**Comment by Yvee1** [comment]
Hey, thanks for the issue. I completely agree that hidden files and directories should be actually hidden by default, and that the user should be able to unhide them if they want. Regarding the symlinks, for me they do appear so that is weird:
![symlink](https://user-images.githubusercontent.com/30909373/88022603-e2f79800-cb2f-11ea-8b65-d6cd74417fdf.png)
Could you double check if they really are not visible for you?

**Comment by Yvee1** [comment]
I just added the hidden files/dirs functionality in commit 1df02a57edc35c189a46bae474e1833495d53964. Somehow Ctrl-h didn't register for me, so I went with regular h for controlling the hidden files instead.

**Comment by RyanGreenup** [comment]
Oh excellent to this fixed.

Yeah so the symlinks do work, you're right, they are at the bottom and so inbetween all my dotfiles I couldn't see them and I I just presumed that they weren't there.
