### ISSUE TITLE
Any plans for incorporating a spaced repetition algorithm?

### ISSUE THREAD

**Issue by bound-variable** [Yvee1/hascard#28]

**Comment by Yvee1** [comment]
No plans currently. Part of the reason is that I don't have a good idea of how to implement it so that it integrates well with the current implementation. Currently each deck of flashcards is just a simple structured text file and there is no metadata associated with it. I like this simplicity and transparancy. For spaced repetition you do require some metadata, either stored in the text file itself or in some hidden file. You can do some limited spaced repetition manually by saving the correct/incorrect cards after reviewing and reviewing them separately as needed.
