### ISSUE TITLE
hascard.exe: thread blocked indefinitely in an STM transaction

### ISSUE THREAD

**Issue by Studywarscat** [Yvee1/hascard#34]
[hascard.exe: thread blocked indefinitely in an STM transaction]
I am in windows
This is the error message that I get when I run hascard under powershell. 
Why is it so? 
It works as administrator .

**Comment by Yvee1** [comment]
This is likely an issue with a library I depend on: [jtdaugherty/brick](https://github.com/jtdaugherty/brick), could you [file an issue there](https://github.com/jtdaugherty/brick/issues/new)? Please mention in the issue that you use Windows. It's easiest if you file an issue because I cannot reproduce the problem on my computer.
